// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArvl5V2a_mtA_yvX5Mg8IZYMm5ZekhHtk',
    appId: '1:612372775315:web:d827036aea09859c8f6866',
    messagingSenderId: '612372775315',
    projectId: 'logintest-8baaf',
    authDomain: 'logintest-8baaf.firebaseapp.com',
    storageBucket: 'logintest-8baaf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1s6kCupZz9GMaOuKRIxP6-eEvuvI3Jnw',
    appId: '1:612372775315:android:b5b76023e553f07d8f6866',
    messagingSenderId: '612372775315',
    projectId: 'logintest-8baaf',
    storageBucket: 'logintest-8baaf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbHjTw_3ckmP8kKqF_7CkUmloNcEDfcf0',
    appId: '1:612372775315:ios:f4c3a583fb5436628f6866',
    messagingSenderId: '612372775315',
    projectId: 'logintest-8baaf',
    storageBucket: 'logintest-8baaf.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbHjTw_3ckmP8kKqF_7CkUmloNcEDfcf0',
    appId: '1:612372775315:ios:b0969408232e89d38f6866',
    messagingSenderId: '612372775315',
    projectId: 'logintest-8baaf',
    storageBucket: 'logintest-8baaf.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );

}
